@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Creating initial commit...
git commit -m "Initial commit for FestPilot"
echo Connecting to GitHub...
git remote add origin https://github.com/DSiddharth24/clubapp
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
